### ISSUE TITLE
NavBar was not changing for the theme

### ISSUE THREAD

**Issue by sethleedy** [Jieiku/theme-dark-arc-gitea#3]
The #navbar at the top of the page was still with a white background.
![image](https://github.com/Jieiku/theme-dark-arc-gitea/assets/11452198/8f883d7e-fc14-402a-9204-42ef7c4b0697)

I tracked down the CSS to the root section. It was simply not there. I included it.

`
:root {
--color-nav-bg: unset;
}
`

![image](https://github.com/Jieiku/theme-dark-arc-gitea/assets/11452198/7cb7fe68-66ff-4097-a6e6-5b3a913ae5f7)

**Comment by Jieiku** [comment]
I merged your pull request, thanks for the heads up, hope to test it myself soon.
