### ISSUE TITLE
there is white stripe :(

### ISSUE THREAD

**Issue by gerroon** [Jieiku/theme-dark-arc-gitea#7]
Thanks for the theme, but unfortunately this creates a white stripe around those menus

![image](https://github.com/Jieiku/theme-dark-arc-gitea/assets/8519469/b126a785-aa17-47c8-a647-bc35450110b7)

**Comment by Jieiku** [comment]
There was a similar issue within the last year that somebody submitted a pull request to fix. It seems to happen when they change things upstream with updates.

**Comment by Jieiku** [comment]
I am not seeing this issue after just now updating my gitea instance to latest (1.21.11) because of another issue: https://github.com/Jieiku/theme-dark-arc-gitea/issues/8

I am assuming whatever was causing the white stripe must have been fixed upstream.
