### ISSUE TITLE
Install Steps Out of Date

### ISSUE THREAD

**Issue by Hi-ImKyle** [Jieiku/theme-dark-arc-gitea#8]
Gitea v1.21.11

Going down the rabbit hole of figuring out where the folder needs to be in order for the CSS files to be picked up fine in a browser but regardless of where I put it, it's always 404 and never loads.

My CustomPath is `/data/gitea`, so the folder for the css files should be `/data/gitea/public/css` but that doesn't appear to work.

I have tried `/data/gitea/public/assets/css` as there was some mention of an assets folder in the Gitea documentation for customization, but that doesn't work either.

I have changed the ownership of the folders and files to the correct user of `git`, as well as added the necessary config information into `app.ini` to make dark-arc selectable but nothing seems to be working.

Any suggestions? Would be a huge help if you knew anything I could try.

**Comment by Hi-ImKyle** [comment]
Ok, I thought I exhausted all options for figuring this out but turns out I didn't and I was almost there for figuring it out before posting this but in any case I have found the issue. 

https://blog.gitea.com/release-of-1.21.0/#%EF%B8%8F-move-public-asset-files-to-the-proper-directory-25907

Rather than download the css file to `$GITEA_CUSTOM/public/css/`, they should be downloaded to `$GITEA_CUSTOM/public/assets/` instead according to the breaking changes for 1.21 stated in the blog post above.

Theme loads just fine now, I suggest you may want to update the installation steps to reflect this.

**Comment by Hi-ImKyle** [comment]
Bit more playing around it does appear to be VERY 50/50 on whether it wants to load a theme, even with it being in the correct spot. But what can you expect..

**Comment by Jieiku** [comment]
Thanks for posting the solution, my gitea instance is still 1.20.3, so I will update soon and update the docs, thanks for posting your findings!

My instance is currently working without issue... but maybe there is something buggy in newer versions, will post back once I get a bit of free time to do all this.

**Comment by Jieiku** [comment]
One thing I will suggest now that you have it working, is to clear your browser cache, that might possibly account for it working 50/50

**Comment by Hi-ImKyle** [comment]
Yeah I think it was cache but not browser. I accidentally had "Cache Assets" on my nginx proxy manager for my gitea route. 

But either way, things still changed. Not massively, just everything in the `$GITEA_CUSTOM/public/assets` folder, rather than just `$GITEA_CUSTOM/public`, if I'm not mistaken. So CSS files going in `../assets/css` now :+1:

**Comment by Jieiku** [comment]
I updated and verified that all is working. Everything looks good so I updated the readme, thanks for the report!
