### ISSUE TITLE
Repository navbar needs a rewrite for Gitea 1.22

### ISSUE THREAD

**Issue by rafal06** [Jieiku/theme-dark-arc-gitea#9]
In Gitea 1.22 the whole repository navbar (now called secondary navbar) was reorganized and restyled, breaking the theme

Screenshot taken with Forgejo, but the same applies to Gitea

![Screenshot 2024-05-02 at 22-08-43 tetris](https://github.com/Jieiku/theme-dark-arc-gitea/assets/70489677/d55ae207-6943-49ae-9d1b-8992fb8fd16b)

**Comment by rafal06** [comment]
Also, tooltips' background is broken

![image](https://github.com/Jieiku/theme-dark-arc-gitea/assets/70489677/e6b72a1d-88b8-44e2-b846-47db564206f0)

**Comment by Jieiku** [comment]
I just updated to 1.21.11 and it looks ok, 1.22 is prerelease but after it has been out for a bit.... maybe 1.22.1 I will see about reworking whatever the default theme is that currently ships into something similar to what this theme provides for 1.21.11

When big changes happen, they tend to iterate and change things quickly, would be good to wait for all those changes to settle down. I am going to add an update to the README indicating as much.

Thank you for the report!

**Comment by rafal06** [comment]
Oh, yeah, I didn't notice Gitea 1.22 isn't out yet. I've updated to Forgejo 7.0, which was released a week ago and it reports Gitea version as 1.22, so I thought it was out already.

But anyways, thanks for making and maintaining this theme!

**Comment by Jieiku** [comment]
Fixed: https://github.com/Jieiku/theme-dark-arc-gitea/pull/10
